### ISSUE TITLE
Setting up the Environment_Variable causes KLayout to crash

### ISSUE THREAD

**Issue by Radioactive-Waste** [shamil777/KLayout-python#6]
Hi shamil,

I have installed the KLayout library according to the readme.txt file. I have created a new environment variable called KLAYOUT_PYTHONPATH and executed the script. I then assigned the output to the variable. After doing so KLayout refuses to open and doesnt show any error messages.

Additional Infos:

- I use Windows 10
- I use python 3.8 with Anaconda
- I use the newest version of KLayout
- This is my output and variable value:

\\network\user\home\Name\Documents\Desktop\Master\CircuitDesign\KLayout-python-master;
C:\Users\Name\Anaconda3\python38.zip;
C:\Users\Name\Anaconda3\DLLs;
C:\Users\Name\Anaconda3\lib;
C:\Users\Name\Anaconda3;
C:\Users\Name\Anaconda3\lib\site-packages;
C:\Users\Name\Anaconda3\lib\site-packages\win32;
C:\Users\Name\Anaconda3\lib\site-packages\win32\lib;
C:\Users\Name\Anaconda3\lib\site-packages\Pythonwin;
\\network\user\home\Name\Documents\Desktop\Master\CircuitDesign\KLayout-python-master

**Comment by shamil777** [comment]
Morning, sir

Looks like your path is including your Anaconda somehow, which is not ok
for KLayout since it has its own python distribution embedded.

I assume you are executing  KLAYOUT_PYTHONPATH.py with your Anaconda python
instead of KLayout's embedded python that is accessible from KLayout
macro-editor (press F5 after startup of KLayout to open it). Klayout's
embedded python has its own libraries paths and only they have to be
present in KLAYOUT_PYTHONPATH.   Try to execute KLAYOUT_PYTHONPATH.py in
this macro-editor.

What is important, you have to do the execution before you created the
environment variable "KLAYOUT_PYTHONPATH". This is due to the fact that if
KLAYOUT_PYTHONPATH environment variable does not include a path to
KLayout's pyhon, the KLayout simply will not start at all.

Just for clarity, though KLayout has it's own python we cannot access it
through some `python.exe` since it is not existing anywhere inside the
KLayout installation directory. Since KLayout uses the
so-called "precompiled" python that is included in "KLayout.exe" at the
compilation time, hence I use the term "embedded python" for it.

If this is not the case, you may verify for me whether or not your Anaconda
distro is included in your windows "PATH" environment variable, which may
interfere in some ways, though they remain subtle to me at the moment.

Looking forward to your progress on this issue, please, notify me if you
make any.

Best regards, Shamil
*_____________________*
*Shamil Kadyrmetov*
*+7 917 515 65 10 (Telegram, WApp)*
*kadyrmetov@phystech.edu <kadyrmetov@phystech.edu>*
*engineer-researcher*
*Laboratory of artificial quantum systems*
*Moscow Institute of Physics and Technology (MIPT)*

**Comment by Radioactive-Waste** [comment]
Dear Shamil,

thank you very much for your detailed answer, it works now. 
Thank you also for clearing up the python and KLayout interplay, continue your great work.

Best Wishes,

Radioactive
